//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScottybonsMVC.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleSKU
    {
        public int ArticleSKUID { get; set; }
        public Nullable<int> ArticleID { get; set; }
        public Nullable<int> ArticleColorID { get; set; }
        public Nullable<int> SizeID { get; set; }
        public decimal CostPrice { get; set; }
        public decimal Margin { get; set; }
        public decimal CurrentRRP { get; set; }
        public decimal OriginalRRP { get; set; }
        public byte[] Stock { get; set; }
        public int NumberReceived { get; set; }
        public int NumberCustSent { get; set; }
        public int NumberCustReturns { get; set; }
        public int NumberReturned { get; set; }
        public int NumberPaid { get; set; }
        public Nullable<int> StatusSKUID { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual ArticleColor ArticleColor { get; set; }
        public virtual SizeMaster SizeMaster { get; set; }
        public virtual SKUStatusMaster SKUStatusMaster { get; set; }
    }
}
