//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScottybonsMVC.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerTypeForm
    {
        public int CustomerTypeID { get; set; }
        public string CustomerStatus { get; set; }
        public string CFirstName { get; set; }
        public string CLastName { get; set; }
        public string CEmailAddress { get; set; }
        public string ScoreStyleBohemian { get; set; }
        public string ScoreStyle2 { get; set; }
        public string ScoreStyle3 { get; set; }
        public string ScoreStyle4 { get; set; }
        public string ScoreStyle5 { get; set; }
        public string ScoreStyle6 { get; set; }
        public string ScoreStyle7 { get; set; }
        public string ScoreStyle8 { get; set; }
        public string ScoreStyle9 { get; set; }
        public string ScoreStyle10 { get; set; }
        public string ScorePants { get; set; }
        public string CommentScorepants { get; set; }
        public string ScoreExperiment { get; set; }
        public string Sector { get; set; }
        public string CommentSector { get; set; }
        public string Function { get; set; }
        public string Transportation { get; set; }
        public string DescriptionWorkDresscode { get; set; }
        public string PerceivedAge { get; set; }
        public Nullable<System.DateTime> CBirthdate { get; set; }
        public string FreqBusiness { get; set; }
        public string OrderOccasion { get; set; }
        public string CommentOrderOccasion { get; set; }
        public string ColorPreference { get; set; }
        public string HairColor { get; set; }
        public string EyeColor { get; set; }
        public string SkinColor { get; set; }
        public string Photograph { get; set; }
        public string ColorAntipathyBlack { get; set; }
        public string ColorAntipathyBrown { get; set; }
        public string ColorAntipathyGreen { get; set; }
        public string ColorAntipathyYellow { get; set; }
        public string ColorAntipathyOrange { get; set; }
        public string ColorAntipathyRed { get; set; }
        public string ColorAntipathyWhite { get; set; }
        public string ColorAntipathyPurple { get; set; }
        public string ColorAntipathyPink { get; set; }
        public string ColorAntipathyGray { get; set; }
        public string ColorAntipathyOther { get; set; }
        public string ColorAntipathyNone { get; set; }
        public string MaterialAntipathyWool { get; set; }
        public string MaterialAntipathyPolyester { get; set; }
        public string MaterialAntipathySilk { get; set; }
        public string MaterialAntipathyViscose { get; set; }
        public string MaterialAntipathyAcryl { get; set; }
        public string MaterialAntipathyNylon { get; set; }
        public string MaterialAntipathyCotton { get; set; }
        public string MaterialAntipathyLinnen { get; set; }
        public string MaterialAntipathyOther { get; set; }
        public string Length { get; set; }
        public string Weight { get; set; }
        public string BodyShape { get; set; }
        public string AccentArms { get; set; }
        public string AccentLegs { get; set; }
        public string AccentBum { get; set; }
        public string AccentWaist { get; set; }
        public string AccentHoulders { get; set; }
        public string AccentDecollet { get; set; }
        public string AccentBoosom { get; set; }
        public string AccentNone { get; set; }
        public string CamouflageUpperarms { get; set; }
        public string CamouflageShoulders { get; set; }
        public string CamouflageNeck { get; set; }
        public string CamouflageBreasts { get; set; }
        public string CamouflageDecollete { get; set; }
        public string CamouflageBelly { get; set; }
        public string CamouflageUpperlegs { get; set; }
        public string CamouflageLowerlegs { get; set; }
        public string CamouflageBum { get; set; }
        public string CamouflageAnkles { get; set; }
        public string SizeTop { get; set; }
        public string CommentSizeTop { get; set; }
        public string SizeCup { get; set; }
        public string CommentSizeCup { get; set; }
        public string FitTop { get; set; }
        public string SizePants { get; set; }
        public string CommentSizePants { get; set; }
        public string FitPants { get; set; }
        public string HighWaistJeans { get; set; }
        public string AverageWaistJeans { get; set; }
        public string LowWaistJeans { get; set; }
        public string SizeShoes { get; set; }
        public string NoHeel { get; set; }
        public string LowHeel { get; set; }
        public string AverageHeel { get; set; }
        public string HighHeel { get; set; }
        public string BudgetBottom { get; set; }
        public string BudgetPumps { get; set; }
        public string BudgetSneakers { get; set; }
        public string BudgetBag { get; set; }
        public string BudgetOutfit { get; set; }
        public string BudgetMonth { get; set; }
        public string ArticleNOTTops { get; set; }
        public string ArticleNOTPants { get; set; }
        public string ArticleNOTSkirt { get; set; }
        public string ArticleNOTDresses { get; set; }
        public string ArticleNOTBlazers { get; set; }
        public string ArticleNOTAccesories { get; set; }
        public string ArticleNOTShoes { get; set; }
        public string ArticleNOTOther { get; set; }
        public string Wishlist { get; set; }
        public string CStreet { get; set; }
        public Nullable<int> CNumber { get; set; }
        public Nullable<int> CPostalcode { get; set; }
        public string CTown { get; set; }
        public string PermissionToCall { get; set; }
        public Nullable<int> CPhoneNumber1 { get; set; }
        public Nullable<System.DateTime> DateStarted { get; set; }
        public Nullable<System.DateTime> DateJoined { get; set; }
        public Nullable<int> NetworkID { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
