//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScottybonsMVC.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailContent
    {
        public int EmailContentID { get; set; }
        public string EmailContentLang { get; set; }
        public int EmailType { get; set; }
        public string EmailTypeDescription { get; set; }
        public string Subject { get; set; }
        public string Intro { get; set; }
        public string BodyMiddle { get; set; }
        public string Closing { get; set; }
        public string EndNote { get; set; }
        public string EmailHTMLFormat { get; set; }
    }
}
