//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScottybonsMVC.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIftCardsOrder
    {
        public int GiftCardOrderId { get; set; }
        public Nullable<long> CustomerType { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string Email { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<double> OrderTotal { get; set; }
        public string PayerFirstName { get; set; }
        public string PayerLastName { get; set; }
        public string ShipmentFirstName { get; set; }
        public string ShipmentLastName { get; set; }
        public string StreetName { get; set; }
        public string HouseNumber { get; set; }
        public string PostalCode { get; set; }
        public string Town { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<int> Status { get; set; }
        public string PaymentId { get; set; }
        public string TransactionId { get; set; }
        public string IssuerType { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public string RandomOrderSuffixer { get; set; }
    }
}
