//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScottybonsMVC.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiftCardRedemption
    {
        public int GiftCardRedemptionId { get; set; }
        public string OrderNumber { get; set; }
        public string GiftCardCode { get; set; }
        public Nullable<double> AmounOfRedemption { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<System.DateTime> RedemptionDateTime { get; set; }
        public Nullable<int> Status { get; set; }
        public string StatusText { get; set; }
    }
}
