//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScottybonsMVC.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int OrderItemID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public int SKUID { get; set; }
        public decimal Price { get; set; }
        public short Quantity { get; set; }
        public decimal Discount { get; set; }
        public decimal Total { get; set; }
        public bool Fulfilled { get; set; }
        public int OrderItemStatusID { get; set; }
        public int SalesTax { get; set; }
        public int VAT { get; set; }
        public Nullable<int> VAT1 { get; set; }
        public string Notes { get; set; }
        public Nullable<int> StylistID { get; set; }
        public string OrderCommentStylist { get; set; }
        public string OrderStyleAdvice { get; set; }
        public Nullable<int> NumberOfArticles { get; set; }
        public string ReviewOverallInformation { get; set; }
        public Nullable<int> OrderItemReviewStyleID { get; set; }
        public Nullable<int> OrderItemReviewSizeID { get; set; }
        public Nullable<int> OrderItemReviewPriceID { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual OrderItemReviewPriceMaster OrderItemReviewPriceMaster { get; set; }
        public virtual OrderItemReviewSizeMaster OrderItemReviewSizeMaster { get; set; }
        public virtual OrderItemReviewStyleMaster OrderItemReviewStyleMaster { get; set; }
        public virtual OrderItemStatusMaster OrderItemStatusMaster { get; set; }
        public virtual Stylist Stylist { get; set; }
    }
}
