//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScottybonsMVC.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPeriodicSubscriptionDetail
    {
        public int OrderPeriodicSubscriptionID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> PeriodicalScottyBoxID { get; set; }
        public Nullable<int> NewPeriodicalScottyBoxID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public bool ChangedByAdmin { get; set; }
        public string AdminId { get; set; }
    }
}
