//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScottybonsMVC.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StyleProfileAnswer
    {
        public int AnswerID { get; set; }
        public Nullable<int> QuestionID { get; set; }
        public string Answer { get; set; }
        public Nullable<int> DependentQuestion { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string AnswerDescription { get; set; }
        public string AnswerImagePath { get; set; }
        public string FLAG { get; set; }
        public string QuestionNumber { get; set; }
        public int AnswerNumber { get; set; }
    }
}
