//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScottybonsMVC.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stylist
    {
        public Stylist()
        {
            this.OrderItems = new HashSet<OrderItem>();
            this.StylistToolTransactions = new HashSet<StylistToolTransaction>();
        }
    
        public int StylistID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PrePosition { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Phone { get; set; }
        public string FAX { get; set; }
        public int Active { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual ICollection<StylistToolTransaction> StylistToolTransactions { get; set; }
    }
}
