//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScottybonsMVC.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StyleProfileQuestion
    {
        public int QuestionID { get; set; }
        public string Question { get; set; }
        public Nullable<int> AnswerControlID { get; set; }
        public string QuestionDescription { get; set; }
        public Nullable<bool> isRequired { get; set; }
        public string ValidationMessage { get; set; }
        public Nullable<bool> IsImageTobeShown { get; set; }
        public Nullable<bool> isDependent { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<short> IsActive { get; set; }
        public string Language { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> QuestionNumber { get; set; }
        public string AdminDescription { get; set; }
    }
}
