//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScottybonsMVC.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierContact
    {
        public int SupplierID { get; set; }
        public int SupplierContactTypeID { get; set; }
        public string SupplierContactTypeName { get; set; }
        public string CPEmailAddress { get; set; }
        public string CPFirstName { get; set; }
        public string CPLastName { get; set; }
        public string CPPreposition { get; set; }
        public string CPFunction { get; set; }
        public string CPStreet { get; set; }
        public decimal CPHouseNumber { get; set; }
        public decimal CPPostalCode { get; set; }
        public decimal CPTown { get; set; }
        public string CPCountry { get; set; }
        public string CPLanguage { get; set; }
        public string CPPhoneNumber1 { get; set; }
        public string CPPhoneNumber2 { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
