//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Validations_en_NL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Validations_en_NL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScottybonsMVC.App_GlobalResources.Validations-en-NL", typeof(Validations_en_NL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lees en accepteer alsjeblieft onze algemene voorwaarden.
        /// </summary>
        public static string AcceptTermsandConditions {
            get {
                return ResourceManager.GetString("AcceptTermsandConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We hebben een stad nodig om te kunnen bezorgen.
        /// </summary>
        public static string CityRequired {
            get {
                return ResourceManager.GetString("CityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oeps, we hebben een geldig e-mailadres nodig….
        /// </summary>
        public static string EmailAddressRequired {
            get {
                return ResourceManager.GetString("EmailAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aj, dit e-mailadres is al in gebruik bij ons….
        /// </summary>
        public static string EmailAlreadyExists {
            get {
                return ResourceManager.GetString("EmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Om jouw wachtwoord te resetten, vul alsjeblieft het email adres waar mee jij je hebt geregistreerd.
        /// </summary>
        public static string EmailNotRegistred {
            get {
                return ResourceManager.GetString("EmailNotRegistred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We hebben je e-mailadres nodig om een account voor je aan te maken.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dit e-mailadres is niet bekend bij ons.
        /// </summary>
        public static string EmailUnknown {
            get {
                return ResourceManager.GetString("EmailUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wil je hier je wachtwoord bevestigen?.
        /// </summary>
        public static string EnterConfirmPassword {
            get {
                return ResourceManager.GetString("EnterConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oeps, je bent je voornaam vergeten.
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geef ons alsjeblieft toestemming om toekomstige facturen te innen (voor de artikelen die je houdt).
        /// </summary>
        public static string InvoicePermission {
            get {
                return ResourceManager.GetString("InvoicePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wat is je vraag of opmerking?.
        /// </summary>
        public static string MessageRequired {
            get {
                return ResourceManager.GetString("MessageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oeps, je bent je naam vergeten….
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laat ons weten voor welke gelegenheid je deze keer een outfit wil ontvangen.
        /// </summary>
        public static string OccasionRequired {
            get {
                return ResourceManager.GetString("OccasionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bedankt voor jouw bestelling. Een bevestiging is momenteel onderweg naar jouw inbox!.
        /// </summary>
        public static string OrderConfirmation {
            get {
                return ResourceManager.GetString("OrderConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vul alsjeblieft hier je wachtwoord in.
        /// </summary>
        public static string PasswordInvalid {
            get {
                return ResourceManager.GetString("PasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kies alsjeblieft een wachtwoord dat minimaal 8 karakters heeft, en minimaal een cijfer bevat.
        /// </summary>
        public static string PasswordInvalidFormat {
            get {
                return ResourceManager.GetString("PasswordInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We hebben een wachtwoord nodig om een account voor je aan te maken.
        /// </summary>
        public static string PasswordIsRequiredForRegistration {
            get {
                return ResourceManager.GetString("PasswordIsRequiredForRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vul je wachtwoord in om in te loggen.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aj, beide wachtwoorden komen niet overeen….
        /// </summary>
        public static string PasswordsNotMatched {
            get {
                return ResourceManager.GetString("PasswordsNotMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oeps, wil je een geldig telefoonnummer invullen? (10 cijfers, bv. 0857500490).
        /// </summary>
        public static string PhoneNumberInValid {
            get {
                return ResourceManager.GetString("PhoneNumberInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Op welk nummer kunnen we je bereiken?.
        /// </summary>
        public static string PhoneNumberRequired {
            get {
                return ResourceManager.GetString("PhoneNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We hebben een postcode nodig om te kunnen bezorgen (Vb formaat: 1234AB).
        /// </summary>
        public static string PostalCodeRequired {
            get {
                return ResourceManager.GetString("PostalCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lees en accepteer alsjeblieft onze privacy policy.
        /// </summary>
        public static string PrivacyPolicyAccept {
            get {
                return ResourceManager.GetString("PrivacyPolicyAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We hebben een straatnaam nodig om te kunnen bezorgen.
        /// </summary>
        public static string StreetNameRequired {
            get {
                return ResourceManager.GetString("StreetNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oeps, je bent je achternaam vergeten.
        /// </summary>
        public static string SurnameRequired {
            get {
                return ResourceManager.GetString("SurnameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wil je het onderwerp invullen?.
        /// </summary>
        public static string TopicRequired {
            get {
                return ResourceManager.GetString("TopicRequired", resourceCulture);
            }
        }
    }
}
