//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.2.93
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

[assembly: PureLiveAssembly, System.Reflection.AssemblyVersion("0.0.0.1")]

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Home</summary>
	[PublishedContentModel("home")]
	public partial class Home : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "home";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Home(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Home, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Content
		///</summary>
		[ImplementPropertyType("content")]
		public Newtonsoft.Json.Linq.JToken Content
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("content"); }
		}
	}

	/// <summary>Contact</summary>
	[PublishedContentModel("contact")]
	public partial class Contact : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "contact";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Contact(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Contact, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Contact Image
		///</summary>
		[ImplementPropertyType("contactImage")]
		public string ContactImage
		{
			get { return this.GetPropertyValue<string>("contactImage"); }
		}

		///<summary>
		/// Document Title: Its language driven (For example for english language, order page title as order, for dutch language order page title as Bestellen)
		///</summary>
		[ImplementPropertyType("documentTitle")]
		public string DocumentTitle
		{
			get { return this.GetPropertyValue<string>("documentTitle"); }
		}
	}

	/// <summary>Order</summary>
	[PublishedContentModel("order")]
	public partial class Order : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "order";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Order(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Order, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Document Title: Its language driven (For example for english language, order page title as order, for dutch language order page title as Bestellen)
		///</summary>
		[ImplementPropertyType("documentTitle")]
		public string DocumentTitle
		{
			get { return this.GetPropertyValue<string>("documentTitle"); }
		}

		///<summary>
		/// Page Hide
		///</summary>
		[ImplementPropertyType("pageHide")]
		public bool PageHide
		{
			get { return this.GetPropertyValue<bool>("pageHide"); }
		}
	}

	/// <summary>ContactUs</summary>
	[PublishedContentModel("contactUs")]
	public partial class ContactUs : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "contactUs";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ContactUs(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContactUs, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>ContactUsConfirmation</summary>
	[PublishedContentModel("contactUs2")]
	public partial class ContactUs2 : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "contactUs2";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ContactUs2(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContactUs2, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Document Title: Its language driven (For example for english language, order page title as order, for dutch language order page title as Bestellen)
		///</summary>
		[ImplementPropertyType("documentTitle")]
		public string DocumentTitle
		{
			get { return this.GetPropertyValue<string>("documentTitle"); }
		}

		///<summary>
		/// Page Hide
		///</summary>
		[ImplementPropertyType("pageHide")]
		public bool PageHide
		{
			get { return this.GetPropertyValue<bool>("pageHide"); }
		}
	}

	/// <summary>OrderThankYou</summary>
	[PublishedContentModel("orderThankYou")]
	public partial class OrderThankYou : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "orderThankYou";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public OrderThankYou(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<OrderThankYou, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// OrderThankYouDescription
		///</summary>
		[ImplementPropertyType("orderThankYouDescription")]
		public IHtmlString OrderThankYouDescription
		{
			get { return this.GetPropertyValue<IHtmlString>("orderThankYouDescription"); }
		}

		///<summary>
		/// OrderThankYouImage
		///</summary>
		[ImplementPropertyType("orderThankYouImage")]
		public object OrderThankYouImage
		{
			get { return this.GetPropertyValue("orderThankYouImage"); }
		}

		///<summary>
		/// Page Hide
		///</summary>
		[ImplementPropertyType("pageHide")]
		public bool PageHide
		{
			get { return this.GetPropertyValue<bool>("pageHide"); }
		}

		///<summary>
		/// Thank You Subheading
		///</summary>
		[ImplementPropertyType("thankYouSubheading")]
		public string ThankYouSubheading
		{
			get { return this.GetPropertyValue<string>("thankYouSubheading"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return this.GetPropertyValue<string>("title"); }
		}
	}

	/// <summary>Account</summary>
	[PublishedContentModel("account")]
	public partial class Account : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "account";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Account(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Account, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Document Title: Its language driven (For example for english language, order page title as order, for dutch language order page title as Bestellen)
		///</summary>
		[ImplementPropertyType("documentTitle")]
		public string DocumentTitle
		{
			get { return this.GetPropertyValue<string>("documentTitle"); }
		}

		///<summary>
		/// Page Hide
		///</summary>
		[ImplementPropertyType("pageHide")]
		public bool PageHide
		{
			get { return this.GetPropertyValue<bool>("pageHide"); }
		}
	}

	/// <summary>Register</summary>
	[PublishedContentModel("register")]
	public partial class Register : Account
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "register";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Register(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Register, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Login</summary>
	[PublishedContentModel("login")]
	public partial class Login : Account
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "login";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Login(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Login, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>OurStory</summary>
	[PublishedContentModel("ourStory")]
	public partial class OurStory : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "ourStory";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public OurStory(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<OurStory, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Content
		///</summary>
		[ImplementPropertyType("content")]
		public Newtonsoft.Json.Linq.JToken Content
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("content"); }
		}
	}

	/// <summary>OurTeam</summary>
	[PublishedContentModel("ourTeam")]
	public partial class OurTeam : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "ourTeam";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public OurTeam(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<OurTeam, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// content
		///</summary>
		[ImplementPropertyType("content")]
		public Newtonsoft.Json.Linq.JToken Content
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("content"); }
		}
	}

	/// <summary>Dashboard</summary>
	[PublishedContentModel("dashboard")]
	public partial class Dashboard : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "dashboard";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Dashboard(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Dashboard, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Document Title: Its language driven (For example for english language, order page title as order, for dutch language order page title as Bestellen)
		///</summary>
		[ImplementPropertyType("documentTitle")]
		public string DocumentTitle
		{
			get { return this.GetPropertyValue<string>("documentTitle"); }
		}

		///<summary>
		/// Page Hide
		///</summary>
		[ImplementPropertyType("pageHide")]
		public bool PageHide
		{
			get { return this.GetPropertyValue<bool>("pageHide"); }
		}
	}

	/// <summary>ScottyBonsHome</summary>
	[PublishedContentModel("scottyBonsHome")]
	public partial class ScottyBonsHome : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "scottyBonsHome";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ScottyBonsHome(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ScottyBonsHome, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Content
		///</summary>
		[ImplementPropertyType("content")]
		public Newtonsoft.Json.Linq.JToken Content
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("content"); }
		}
	}

	/// <summary>StyleProfile</summary>
	[PublishedContentModel("styleProfile")]
	public partial class StyleProfile : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "styleProfile";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public StyleProfile(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<StyleProfile, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>ConfirmYourOrder</summary>
	[PublishedContentModel("yourOrder")]
	public partial class YourOrder : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "yourOrder";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public YourOrder(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<YourOrder, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>GeneralConditions</summary>
	[PublishedContentModel("generalConditions")]
	public partial class GeneralConditions : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "generalConditions";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public GeneralConditions(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<GeneralConditions, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Content
		///</summary>
		[ImplementPropertyType("content")]
		public Newtonsoft.Json.Linq.JToken Content
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("content"); }
		}
	}

	/// <summary>Terms&Conditions</summary>
	[PublishedContentModel("terms")]
	public partial class Terms : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "terms";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Terms(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Terms, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Content
		///</summary>
		[ImplementPropertyType("content")]
		public Newtonsoft.Json.Linq.JToken Content
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("content"); }
		}

		///<summary>
		/// Page Hide
		///</summary>
		[ImplementPropertyType("pageHide")]
		public bool PageHide
		{
			get { return this.GetPropertyValue<bool>("pageHide"); }
		}
	}

	/// <summary>Vacancies</summary>
	[PublishedContentModel("vacancies")]
	public partial class Vacancies : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "vacancies";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Vacancies(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Vacancies, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Content
		///</summary>
		[ImplementPropertyType("content")]
		public Newtonsoft.Json.Linq.JToken Content
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("content"); }
		}

		///<summary>
		/// Page Hide
		///</summary>
		[ImplementPropertyType("pageHide")]
		public bool PageHide
		{
			get { return this.GetPropertyValue<bool>("pageHide"); }
		}
	}

	/// <summary>StyleTips</summary>
	[PublishedContentModel("styleTips")]
	public partial class StyleTips : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "styleTips";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public StyleTips(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<StyleTips, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Content
		///</summary>
		[ImplementPropertyType("content")]
		public Newtonsoft.Json.Linq.JToken Content
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("content"); }
		}

		///<summary>
		/// Page Hide
		///</summary>
		[ImplementPropertyType("pageHide")]
		public bool PageHide
		{
			get { return this.GetPropertyValue<bool>("pageHide"); }
		}
	}

	/// <summary>Reviews</summary>
	[PublishedContentModel("reviews")]
	public partial class Reviews : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "reviews";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Reviews(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Reviews, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Content
		///</summary>
		[ImplementPropertyType("content")]
		public Newtonsoft.Json.Linq.JToken Content
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("content"); }
		}

		///<summary>
		/// Page Hide
		///</summary>
		[ImplementPropertyType("pageHide")]
		public bool PageHide
		{
			get { return this.GetPropertyValue<bool>("pageHide"); }
		}
	}

	/// <summary>Gen Folder</summary>
	[PublishedContentModel("genFolder")]
	public partial class GenFolder : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "genFolder";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public GenFolder(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<GenFolder, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>ScotyBonsBase</summary>
	[PublishedContentModel("scotyBonsBase")]
	public partial class ScotyBonsBase : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "scotyBonsBase";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ScotyBonsBase(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ScotyBonsBase, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Document Title: Its language driven (For example for english language, order page title as order, for dutch language order page title as Bestellen)
		///</summary>
		[ImplementPropertyType("documentTitle")]
		public string DocumentTitle
		{
			get { return this.GetPropertyValue<string>("documentTitle"); }
		}

		///<summary>
		/// Page Description
		///</summary>
		[ImplementPropertyType("pageDescription")]
		public string PageDescription
		{
			get { return this.GetPropertyValue<string>("pageDescription"); }
		}

		///<summary>
		/// Page Hide
		///</summary>
		[ImplementPropertyType("pageHide")]
		public bool PageHide
		{
			get { return this.GetPropertyValue<bool>("pageHide"); }
		}

		///<summary>
		/// Page Title
		///</summary>
		[ImplementPropertyType("pageTitle")]
		public string PageTitle
		{
			get { return this.GetPropertyValue<string>("pageTitle"); }
		}
	}

	/// <summary>ScottyBonsHomeNode</summary>
	[PublishedContentModel("scottyBonsHomeNode")]
	public partial class ScottyBonsHomeNode : ScotyBonsBase
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "scottyBonsHomeNode";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ScottyBonsHomeNode(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ScottyBonsHomeNode, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Anchor Text
		///</summary>
		[ImplementPropertyType("anchorText")]
		public string AnchorText
		{
			get { return this.GetPropertyValue<string>("anchorText"); }
		}

		///<summary>
		/// Banner Image
		///</summary>
		[ImplementPropertyType("bannerImage")]
		public string BannerImage
		{
			get { return this.GetPropertyValue<string>("bannerImage"); }
		}

		///<summary>
		/// Banner Image Content
		///</summary>
		[ImplementPropertyType("bannerImageContent")]
		public IHtmlString BannerImageContent
		{
			get { return this.GetPropertyValue<IHtmlString>("bannerImageContent"); }
		}

		///<summary>
		/// Brands Promos
		///</summary>
		[ImplementPropertyType("brandsPromos")]
		public object BrandsPromos
		{
			get { return this.GetPropertyValue("brandsPromos"); }
		}

		///<summary>
		/// Carousel Promos
		///</summary>
		[ImplementPropertyType("carouselPromos")]
		public object CarouselPromos
		{
			get { return this.GetPropertyValue("carouselPromos"); }
		}

		///<summary>
		/// Footer promos
		///</summary>
		[ImplementPropertyType("footerPromos")]
		public object FooterPromos
		{
			get { return this.GetPropertyValue("footerPromos"); }
		}

		///<summary>
		/// Redirection Link
		///</summary>
		[ImplementPropertyType("redirectionLink")]
		public object RedirectionLink
		{
			get { return this.GetPropertyValue("redirectionLink"); }
		}

		///<summary>
		/// Row1 Promos
		///</summary>
		[ImplementPropertyType("row1Promos")]
		public object Row1Promos
		{
			get { return this.GetPropertyValue("row1Promos"); }
		}

		///<summary>
		/// Row2 Promo
		///</summary>
		[ImplementPropertyType("row2Promo")]
		public object Row2Promo
		{
			get { return this.GetPropertyValue("row2Promo"); }
		}

		///<summary>
		/// Row3Promo
		///</summary>
		[ImplementPropertyType("row3Promo")]
		public object Row3Promo
		{
			get { return this.GetPropertyValue("row3Promo"); }
		}

		///<summary>
		/// Who are we Promos
		///</summary>
		[ImplementPropertyType("whoAreWePromos")]
		public object WhoAreWePromos
		{
			get { return this.GetPropertyValue("whoAreWePromos"); }
		}
	}

	/// <summary>ScottyBonsSubMenus</summary>
	[PublishedContentModel("scottyBonsSubMenus")]
	public partial class ScottyBonsSubMenus : ScotyBonsBase
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "scottyBonsSubMenus";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ScottyBonsSubMenus(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ScottyBonsSubMenus, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Home Page Row1</summary>
	[PublishedContentModel("homePageRow1")]
	public partial class HomePageRow1 : GenFolder
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "homePageRow1";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HomePageRow1(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HomePageRow1, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Promo Content
		///</summary>
		[ImplementPropertyType("promoContent")]
		public IHtmlString PromoContent
		{
			get { return this.GetPropertyValue<IHtmlString>("promoContent"); }
		}

		///<summary>
		/// Promo Sub Heading
		///</summary>
		[ImplementPropertyType("promoSubHeading")]
		public string PromoSubHeading
		{
			get { return this.GetPropertyValue<string>("promoSubHeading"); }
		}

		///<summary>
		/// Promo Title: This is for H1 Main heading
		///</summary>
		[ImplementPropertyType("promoTitle")]
		public string PromoTitle
		{
			get { return this.GetPropertyValue<string>("promoTitle"); }
		}
	}

	/// <summary>Home Brands</summary>
	[PublishedContentModel("homeBrands")]
	public partial class HomeBrands : GenFolder
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "homeBrands";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HomeBrands(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HomeBrands, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Brand Image
		///</summary>
		[ImplementPropertyType("brandImage")]
		public string BrandImage
		{
			get { return this.GetPropertyValue<string>("brandImage"); }
		}

		///<summary>
		/// Redirection Link
		///</summary>
		[ImplementPropertyType("redirectionLink")]
		public object RedirectionLink
		{
			get { return this.GetPropertyValue("redirectionLink"); }
		}
	}

	/// <summary>Home Carousel Item</summary>
	[PublishedContentModel("homeCarouselItem")]
	public partial class HomeCarouselItem : GenFolder
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "homeCarouselItem";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HomeCarouselItem(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HomeCarouselItem, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Carousel Image
		///</summary>
		[ImplementPropertyType("carouselImage")]
		public string CarouselImage
		{
			get { return this.GetPropertyValue<string>("carouselImage"); }
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("description")]
		public IHtmlString Description
		{
			get { return this.GetPropertyValue<IHtmlString>("description"); }
		}

		///<summary>
		/// Redirection Link
		///</summary>
		[ImplementPropertyType("redirectionLink")]
		public object RedirectionLink
		{
			get { return this.GetPropertyValue("redirectionLink"); }
		}

		///<summary>
		/// Redirection Link Title
		///</summary>
		[ImplementPropertyType("redirectionLinkTitle")]
		public string RedirectionLinkTitle
		{
			get { return this.GetPropertyValue<string>("redirectionLinkTitle"); }
		}
	}

	/// <summary>Products</summary>
	[PublishedContentModel("products")]
	public partial class Products : ScotyBonsBase
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "products";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Products(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Products, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Who are we Document Type</summary>
	[PublishedContentModel("whoAreWeDocumentType")]
	public partial class WhoAreWeDocumentType : GenFolder
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "whoAreWeDocumentType";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public WhoAreWeDocumentType(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<WhoAreWeDocumentType, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Who are we description
		///</summary>
		[ImplementPropertyType("whoAreWeDescription")]
		public IHtmlString WhoAreWeDescription
		{
			get { return this.GetPropertyValue<IHtmlString>("whoAreWeDescription"); }
		}

		///<summary>
		/// Who are we heading
		///</summary>
		[ImplementPropertyType("whoAreWeHeading")]
		public string WhoAreWeHeading
		{
			get { return this.GetPropertyValue<string>("whoAreWeHeading"); }
		}

		///<summary>
		/// Who are we Image
		///</summary>
		[ImplementPropertyType("whoAreWeImage")]
		public string WhoAreWeImage
		{
			get { return this.GetPropertyValue<string>("whoAreWeImage"); }
		}
	}

	/// <summary>Footer Link Promo</summary>
	[PublishedContentModel("footerLinkPromo")]
	public partial class FooterLinkPromo : GenFolder
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "footerLinkPromo";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public FooterLinkPromo(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<FooterLinkPromo, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Footer Link Title
		///</summary>
		[ImplementPropertyType("footerLinkTitle")]
		public string FooterLinkTitle
		{
			get { return this.GetPropertyValue<string>("footerLinkTitle"); }
		}

		///<summary>
		/// Footer Redirection Ext link
		///</summary>
		[ImplementPropertyType("footerRedirectionExtLink")]
		public string FooterRedirectionExtLink
		{
			get { return this.GetPropertyValue<string>("footerRedirectionExtLink"); }
		}

		///<summary>
		/// Footer Redirection link
		///</summary>
		[ImplementPropertyType("footerRedirectionLink")]
		public object FooterRedirectionLink
		{
			get { return this.GetPropertyValue("footerRedirectionLink"); }
		}

		///<summary>
		/// Is External Window
		///</summary>
		[ImplementPropertyType("isExternalWindow")]
		public bool IsExternalWindow
		{
			get { return this.GetPropertyValue<bool>("isExternalWindow"); }
		}
	}

	/// <summary>FAQ Page</summary>
	[PublishedContentModel("fAQPage")]
	public partial class FAqpage : ScotyBonsBase
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "fAQPage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public FAqpage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<FAqpage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// FAQ Promos
		///</summary>
		[ImplementPropertyType("fAQPromos")]
		public object FAqpromos
		{
			get { return this.GetPropertyValue("fAQPromos"); }
		}
	}

	/// <summary>FAQ Questions</summary>
	[PublishedContentModel("fAQQuestions")]
	public partial class FAqquestions : GenFolder
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "fAQQuestions";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public FAqquestions(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<FAqquestions, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// FAQ Answer
		///</summary>
		[ImplementPropertyType("fAQAnswer")]
		public IHtmlString FAqanswer
		{
			get { return this.GetPropertyValue<IHtmlString>("fAQAnswer"); }
		}

		///<summary>
		/// FAQ Question
		///</summary>
		[ImplementPropertyType("fAQQuestion")]
		public string FAqquestion
		{
			get { return this.GetPropertyValue<string>("fAQQuestion"); }
		}
	}

	/// <summary>Our Story Snippets</summary>
	[PublishedContentModel("ourStorySnippets")]
	public partial class OurStorySnippets : GenFolder
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "ourStorySnippets";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public OurStorySnippets(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<OurStorySnippets, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Our Story Description
		///</summary>
		[ImplementPropertyType("ourStoryDescription")]
		public IHtmlString OurStoryDescription
		{
			get { return this.GetPropertyValue<IHtmlString>("ourStoryDescription"); }
		}

		///<summary>
		/// Our Story Image
		///</summary>
		[ImplementPropertyType("ourStoryImage")]
		public object OurStoryImage
		{
			get { return this.GetPropertyValue("ourStoryImage"); }
		}

		///<summary>
		/// Our Story Title
		///</summary>
		[ImplementPropertyType("ourStoryTitle")]
		public string OurStoryTitle
		{
			get { return this.GetPropertyValue<string>("ourStoryTitle"); }
		}
	}

	/// <summary>Our Story Page</summary>
	[PublishedContentModel("ourStoryPage")]
	public partial class OurStoryPage : ScotyBonsBase
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "ourStoryPage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public OurStoryPage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<OurStoryPage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Our Story Promos
		///</summary>
		[ImplementPropertyType("ourStoryPromos")]
		public object OurStoryPromos
		{
			get { return this.GetPropertyValue("ourStoryPromos"); }
		}
	}

	/// <summary>Our  team snippets</summary>
	[PublishedContentModel("ourTeamSnippets")]
	public partial class OurTeamSnippets : GenFolder
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "ourTeamSnippets";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public OurTeamSnippets(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<OurTeamSnippets, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("description")]
		public IHtmlString Description
		{
			get { return this.GetPropertyValue<IHtmlString>("description"); }
		}

		///<summary>
		/// Image
		///</summary>
		[ImplementPropertyType("image")]
		public object Image
		{
			get { return this.GetPropertyValue("image"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return this.GetPropertyValue<string>("title"); }
		}
	}

	/// <summary>Our Team Page</summary>
	[PublishedContentModel("ourTeamPage")]
	public partial class OurTeamPage : ScotyBonsBase
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "ourTeamPage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public OurTeamPage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<OurTeamPage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Our Team Promos
		///</summary>
		[ImplementPropertyType("ourTeamPromos")]
		public object OurTeamPromos
		{
			get { return this.GetPropertyValue("ourTeamPromos"); }
		}
	}

	/// <summary>Joining ScottyBons Questions</summary>
	[PublishedContentModel("joiningScottyBonsQuestions")]
	public partial class JoiningScottyBonsQuestions : GenFolder
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "joiningScottyBonsQuestions";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public JoiningScottyBonsQuestions(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<JoiningScottyBonsQuestions, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Joining ScottyBons Posting Details
		///</summary>
		[ImplementPropertyType("joiningScottyBonsAnswer")]
		public IHtmlString JoiningScottyBonsAnswer
		{
			get { return this.GetPropertyValue<IHtmlString>("joiningScottyBonsAnswer"); }
		}

		///<summary>
		/// Joining ScottyBons Posting
		///</summary>
		[ImplementPropertyType("joiningScottyBonsQuestion")]
		public string JoiningScottyBonsQuestion
		{
			get { return this.GetPropertyValue<string>("joiningScottyBonsQuestion"); }
		}
	}

	/// <summary>Joining ScottyBons Page</summary>
	[PublishedContentModel("joiningScottyBonsPage")]
	public partial class JoiningScottyBonsPage : ScotyBonsBase
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "joiningScottyBonsPage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public JoiningScottyBonsPage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<JoiningScottyBonsPage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Scotty Bons Promos
		///</summary>
		[ImplementPropertyType("scottyBonsPromos")]
		public object ScottyBonsPromos
		{
			get { return this.GetPropertyValue("scottyBonsPromos"); }
		}
	}

	/// <summary>Error Page</summary>
	[PublishedContentModel("errorPage")]
	public partial class ErrorPage : ScotyBonsBase
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "errorPage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ErrorPage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ErrorPage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Press Page</summary>
	[PublishedContentModel("pressPage")]
	public partial class PressPage : ScotyBonsBase
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "pressPage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public PressPage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<PressPage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Heading
		///</summary>
		[ImplementPropertyType("heading")]
		public string Heading
		{
			get { return this.GetPropertyValue<string>("heading"); }
		}

		///<summary>
		/// Press Image Promos
		///</summary>
		[ImplementPropertyType("pressImagePromos")]
		public object PressImagePromos
		{
			get { return this.GetPropertyValue("pressImagePromos"); }
		}

		///<summary>
		/// Press Question Promos
		///</summary>
		[ImplementPropertyType("pressQuestionPromos")]
		public object PressQuestionPromos
		{
			get { return this.GetPropertyValue("pressQuestionPromos"); }
		}

		///<summary>
		/// Sub Heading
		///</summary>
		[ImplementPropertyType("subHeading")]
		public string SubHeading
		{
			get { return this.GetPropertyValue<string>("subHeading"); }
		}
	}

	/// <summary>Press Page Image Snippets</summary>
	[PublishedContentModel("pressPageImageSnippets")]
	public partial class PressPageImageSnippets : GenFolder
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "pressPageImageSnippets";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public PressPageImageSnippets(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<PressPageImageSnippets, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// PressImage
		///</summary>
		[ImplementPropertyType("pressImage")]
		public string PressImage
		{
			get { return this.GetPropertyValue<string>("pressImage"); }
		}

		///<summary>
		/// Press Redirection Link
		///</summary>
		[ImplementPropertyType("pressRedirectionLink")]
		public object PressRedirectionLink
		{
			get { return this.GetPropertyValue("pressRedirectionLink"); }
		}
	}

	/// <summary>Press Page Questions</summary>
	[PublishedContentModel("pressPageQuestions")]
	public partial class PressPageQuestions : GenFolder
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "pressPageQuestions";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public PressPageQuestions(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<PressPageQuestions, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Press Answer
		///</summary>
		[ImplementPropertyType("pressAnswer")]
		public IHtmlString PressAnswer
		{
			get { return this.GetPropertyValue<IHtmlString>("pressAnswer"); }
		}

		///<summary>
		/// Press Question
		///</summary>
		[ImplementPropertyType("pressQuestion")]
		public string PressQuestion
		{
			get { return this.GetPropertyValue<string>("pressQuestion"); }
		}
	}

	/// <summary>Style Tips Snippets</summary>
	[PublishedContentModel("styleTipsSnippets")]
	public partial class StyleTipsSnippets : GenFolder
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "styleTipsSnippets";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public StyleTipsSnippets(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<StyleTipsSnippets, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Style Tips Date
		///</summary>
		[ImplementPropertyType("styleTipsDate")]
		public DateTime StyleTipsDate
		{
			get { return this.GetPropertyValue<DateTime>("styleTipsDate"); }
		}

		///<summary>
		/// Style Tips Description
		///</summary>
		[ImplementPropertyType("styleTipsDescription")]
		public IHtmlString StyleTipsDescription
		{
			get { return this.GetPropertyValue<IHtmlString>("styleTipsDescription"); }
		}

		///<summary>
		/// Style Tips Image
		///</summary>
		[ImplementPropertyType("styleTipsImage")]
		public object StyleTipsImage
		{
			get { return this.GetPropertyValue("styleTipsImage"); }
		}

		///<summary>
		/// Style Tips Title
		///</summary>
		[ImplementPropertyType("styleTipsTitle")]
		public string StyleTipsTitle
		{
			get { return this.GetPropertyValue<string>("styleTipsTitle"); }
		}
	}

	/// <summary>Style Tips Page</summary>
	[PublishedContentModel("styleTipsPage")]
	public partial class StyleTipsPage : ScotyBonsBase
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "styleTipsPage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public StyleTipsPage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<StyleTipsPage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Style Tips Promos
		///</summary>
		[ImplementPropertyType("styleTipsPromos")]
		public object StyleTipsPromos
		{
			get { return this.GetPropertyValue("styleTipsPromos"); }
		}
	}

	/// <summary>Reviews Snippet</summary>
	[PublishedContentModel("reviewsSnippet")]
	public partial class ReviewsSnippet : GenFolder
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "reviewsSnippet";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ReviewsSnippet(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ReviewsSnippet, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Review Date
		///</summary>
		[ImplementPropertyType("reviewDate")]
		public DateTime ReviewDate
		{
			get { return this.GetPropertyValue<DateTime>("reviewDate"); }
		}

		///<summary>
		/// Review Description
		///</summary>
		[ImplementPropertyType("reviewDescription")]
		public IHtmlString ReviewDescription
		{
			get { return this.GetPropertyValue<IHtmlString>("reviewDescription"); }
		}

		///<summary>
		/// Review Title
		///</summary>
		[ImplementPropertyType("reviewTitle")]
		public string ReviewTitle
		{
			get { return this.GetPropertyValue<string>("reviewTitle"); }
		}
	}

	/// <summary>Reviews Page</summary>
	[PublishedContentModel("reviewsPage")]
	public partial class ReviewsPage : ScotyBonsBase
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "reviewsPage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ReviewsPage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ReviewsPage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Review Promos
		///</summary>
		[ImplementPropertyType("reviewPromos")]
		public object ReviewPromos
		{
			get { return this.GetPropertyValue("reviewPromos"); }
		}
	}

	/// <summary>Terms and Conditions</summary>
	[PublishedContentModel("termsAndConditions")]
	public partial class TermsAndConditions : ScotyBonsBase
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "termsAndConditions";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public TermsAndConditions(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<TermsAndConditions, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Terms and Conditions Description
		///</summary>
		[ImplementPropertyType("termsAndConditionsDescription")]
		public IHtmlString TermsAndConditionsDescription
		{
			get { return this.GetPropertyValue<IHtmlString>("termsAndConditionsDescription"); }
		}

		///<summary>
		/// Terms and Conditions Title
		///</summary>
		[ImplementPropertyType("termsAndConditionsTitle")]
		public string TermsAndConditionsTitle
		{
			get { return this.GetPropertyValue<string>("termsAndConditionsTitle"); }
		}
	}

	/// <summary>Privacy Policy</summary>
	[PublishedContentModel("privacyPolicy")]
	public partial class PrivacyPolicy : ScotyBonsBase
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "privacyPolicy";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public PrivacyPolicy(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<PrivacyPolicy, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Privacy Policy Description
		///</summary>
		[ImplementPropertyType("privacyPolicyDescription")]
		public IHtmlString PrivacyPolicyDescription
		{
			get { return this.GetPropertyValue<IHtmlString>("privacyPolicyDescription"); }
		}

		///<summary>
		/// Privacy policy Tiltle
		///</summary>
		[ImplementPropertyType("privacyPolicyTiltle")]
		public string PrivacyPolicyTiltle
		{
			get { return this.GetPropertyValue<string>("privacyPolicyTiltle"); }
		}
	}

	/// <summary>MyAccount</summary>
	[PublishedContentModel("myAccount")]
	public partial class MyAccount : Account
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "myAccount";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public MyAccount(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<MyAccount, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Content
		///</summary>
		[ImplementPropertyType("content")]
		public string Content
		{
			get { return this.GetPropertyValue<string>("content"); }
		}
	}

	/// <summary>Social Media Page</summary>
	[PublishedContentModel("socialMediaPage")]
	public partial class SocialMediaPage : ScotyBonsBase
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "socialMediaPage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SocialMediaPage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SocialMediaPage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>StyleProfileQA</summary>
	[PublishedContentModel("styleProfileQA")]
	public partial class StyleProfileQA : ScotyBonsBase
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "styleProfileQA";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public StyleProfileQA(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<StyleProfileQA, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>ProfileQuestions</summary>
	[PublishedContentModel("profileQuestions")]
	public partial class ProfileQuestions : Account
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "profileQuestions";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ProfileQuestions(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ProfileQuestions, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>EditProfileQuestions</summary>
	[PublishedContentModel("editProfileQuestions")]
	public partial class EditProfileQuestions : Account
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "editProfileQuestions";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public EditProfileQuestions(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<EditProfileQuestions, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Change Password</summary>
	[PublishedContentModel("changePassword")]
	public partial class ChangePassword : Account
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "changePassword";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ChangePassword(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ChangePassword, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>MySubscription</summary>
	[PublishedContentModel("mySubscription")]
	public partial class MySubscription : Account
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "mySubscription";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public MySubscription(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<MySubscription, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Delivery Address Text
		///</summary>
		[ImplementPropertyType("deliveryAddressText")]
		public string DeliveryAddressText
		{
			get { return this.GetPropertyValue<string>("deliveryAddressText"); }
		}

		///<summary>
		/// Delivery At Neighbour Text
		///</summary>
		[ImplementPropertyType("deliveryAtNeighbourText")]
		public string DeliveryAtNeighbourText
		{
			get { return this.GetPropertyValue<string>("deliveryAtNeighbourText"); }
		}

		///<summary>
		/// Delivery Duration Note Text
		///</summary>
		[ImplementPropertyType("deliveryDurationNoteText")]
		public string DeliveryDurationNoteText
		{
			get { return this.GetPropertyValue<string>("deliveryDurationNoteText"); }
		}

		///<summary>
		/// Edit Button Text
		///</summary>
		[ImplementPropertyType("editButtonText")]
		public string EditButtonText
		{
			get { return this.GetPropertyValue<string>("editButtonText"); }
		}

		///<summary>
		/// How to Change Note
		///</summary>
		[ImplementPropertyType("howToChangeNote")]
		public string HowToChangeNote
		{
			get { return this.GetPropertyValue<string>("howToChangeNote"); }
		}

		///<summary>
		/// Occasion List
		///</summary>
		[ImplementPropertyType("occasionList")]
		public object OccasionList
		{
			get { return this.GetPropertyValue("occasionList"); }
		}

		///<summary>
		/// Occasion Text
		///</summary>
		[ImplementPropertyType("occasionText")]
		public string OccasionText
		{
			get { return this.GetPropertyValue<string>("occasionText"); }
		}

		///<summary>
		/// Page subtitle
		///</summary>
		[ImplementPropertyType("pageSubtitle")]
		public string PageSubtitle
		{
			get { return this.GetPropertyValue<string>("pageSubtitle"); }
		}

		///<summary>
		/// Page Title
		///</summary>
		[ImplementPropertyType("pageTitle")]
		public string PageTitle
		{
			get { return this.GetPropertyValue<string>("pageTitle"); }
		}

		///<summary>
		/// Phone Number Text
		///</summary>
		[ImplementPropertyType("phoneNumberText")]
		public string PhoneNumberText
		{
			get { return this.GetPropertyValue<string>("phoneNumberText"); }
		}

		///<summary>
		/// Save Button Text
		///</summary>
		[ImplementPropertyType("saveButtonText")]
		public string SaveButtonText
		{
			get { return this.GetPropertyValue<string>("saveButtonText"); }
		}

		///<summary>
		/// Next Scottybox is planned date text
		///</summary>
		[ImplementPropertyType("selectPeriod")]
		public string SelectPeriod
		{
			get { return this.GetPropertyValue<string>("selectPeriod"); }
		}

		///<summary>
		/// Send Me Scottybox Checkbox
		///</summary>
		[ImplementPropertyType("sendMeScottyboxCheckcbox")]
		public bool SendMeScottyboxCheckcbox
		{
			get { return this.GetPropertyValue<bool>("sendMeScottyboxCheckcbox"); }
		}

		///<summary>
		/// Send me Scottybox Text
		///</summary>
		[ImplementPropertyType("sendMeScottyboxText")]
		public string SendMeScottyboxText
		{
			get { return this.GetPropertyValue<string>("sendMeScottyboxText"); }
		}

		///<summary>
		/// Subscription Type List EN
		///</summary>
		[ImplementPropertyType("subscriptionTypeList")]
		public object SubscriptionTypeList
		{
			get { return this.GetPropertyValue("subscriptionTypeList"); }
		}

		///<summary>
		/// Subscription Type List NL
		///</summary>
		[ImplementPropertyType("subscriptionTypeListNL")]
		public object SubscriptionTypeListNL
		{
			get { return this.GetPropertyValue("subscriptionTypeListNL"); }
		}
	}

	/// <summary>GiftCard</summary>
	[PublishedContentModel("giftCard")]
	public partial class GiftCard : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "giftCard";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public GiftCard(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<GiftCard, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// DocumentTitle
		///</summary>
		[ImplementPropertyType("documentTitle")]
		public string DocumentTitle
		{
			get { return this.GetPropertyValue<string>("documentTitle"); }
		}

		///<summary>
		/// Process Image
		///</summary>
		[ImplementPropertyType("processImage")]
		public string ProcessImage
		{
			get { return this.GetPropertyValue<string>("processImage"); }
		}

		///<summary>
		/// Process Text
		///</summary>
		[ImplementPropertyType("processText")]
		public IHtmlString ProcessText
		{
			get { return this.GetPropertyValue<IHtmlString>("processText"); }
		}

		///<summary>
		/// Process Text One
		///</summary>
		[ImplementPropertyType("processTextOne")]
		public IHtmlString ProcessTextOne
		{
			get { return this.GetPropertyValue<IHtmlString>("processTextOne"); }
		}

		///<summary>
		/// Process Text Two
		///</summary>
		[ImplementPropertyType("processTextTwo")]
		public IHtmlString ProcessTextTwo
		{
			get { return this.GetPropertyValue<IHtmlString>("processTextTwo"); }
		}

		///<summary>
		/// Process Title
		///</summary>
		[ImplementPropertyType("processTitle")]
		public string ProcessTitle
		{
			get { return this.GetPropertyValue<string>("processTitle"); }
		}
	}

	/// <summary>Promocodes</summary>
	[PublishedContentModel("promocodes")]
	public partial class Promocodes : Order
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "promocodes";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Promocodes(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Promocodes, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Promocode</summary>
	[PublishedContentModel("promocode")]
	public partial class Promocode : Promocodes
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "promocode";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Promocode(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Promocode, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// AllowAllUsers
		///</summary>
		[ImplementPropertyType("allowAllUsers")]
		public bool AllowAllUsers
		{
			get { return this.GetPropertyValue<bool>("allowAllUsers"); }
		}

		///<summary>
		/// EndDate
		///</summary>
		[ImplementPropertyType("endDate")]
		public DateTime EndDate
		{
			get { return this.GetPropertyValue<DateTime>("endDate"); }
		}

		///<summary>
		/// IsEnable
		///</summary>
		[ImplementPropertyType("isEnable")]
		public bool IsEnable
		{
			get { return this.GetPropertyValue<bool>("isEnable"); }
		}

		///<summary>
		/// IsOnline
		///</summary>
		[ImplementPropertyType("isOnline")]
		public bool IsOnline
		{
			get { return this.GetPropertyValue<bool>("isOnline"); }
		}

		///<summary>
		/// IsPercentage
		///</summary>
		[ImplementPropertyType("isPercentage")]
		public bool IsPercentage
		{
			get { return this.GetPropertyValue<bool>("isPercentage"); }
		}

		///<summary>
		/// OnlyOnce
		///</summary>
		[ImplementPropertyType("onlyOnce")]
		public bool OnlyOnce
		{
			get { return this.GetPropertyValue<bool>("onlyOnce"); }
		}

		///<summary>
		/// Promo Code Name
		///</summary>
		[ImplementPropertyType("promoCodeName")]
		public string PromoCodeName
		{
			get { return this.GetPropertyValue<string>("promoCodeName"); }
		}

		///<summary>
		/// Promo Code Value
		///</summary>
		[ImplementPropertyType("promoCodeValue")]
		public int PromoCodeValue
		{
			get { return this.GetPropertyValue<int>("promoCodeValue"); }
		}

		///<summary>
		/// StartDate
		///</summary>
		[ImplementPropertyType("startDate")]
		public DateTime StartDate
		{
			get { return this.GetPropertyValue<DateTime>("startDate"); }
		}
	}

	/// <summary>PromoCodeTypes</summary>
	[PublishedContentModel("promoCodeTypes")]
	public partial class PromoCodeTypes : Promocodes
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "promoCodeTypes";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public PromoCodeTypes(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<PromoCodeTypes, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>PromoCodeType</summary>
	[PublishedContentModel("promoCodeType")]
	public partial class PromoCodeType : PromoCodeTypes
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "promoCodeType";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public PromoCodeType(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<PromoCodeType, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("type")]
		public string Type
		{
			get { return this.GetPropertyValue<string>("type"); }
		}
	}

	/// <summary>Folder</summary>
	[PublishedContentModel("Folder")]
	public partial class Folder : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Folder";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Folder(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Folder, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Contents:
		///</summary>
		[ImplementPropertyType("contents")]
		public object Contents
		{
			get { return this.GetPropertyValue("contents"); }
		}
	}

	/// <summary>Image</summary>
	[PublishedContentModel("Image")]
	public partial class Image : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Image";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Image(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Image, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload image
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public object UmbracoFile
		{
			get { return this.GetPropertyValue("umbracoFile"); }
		}

		///<summary>
		/// Height
		///</summary>
		[ImplementPropertyType("umbracoHeight")]
		public string UmbracoHeight
		{
			get { return this.GetPropertyValue<string>("umbracoHeight"); }
		}

		///<summary>
		/// Width
		///</summary>
		[ImplementPropertyType("umbracoWidth")]
		public string UmbracoWidth
		{
			get { return this.GetPropertyValue<string>("umbracoWidth"); }
		}
	}

	/// <summary>File</summary>
	[PublishedContentModel("File")]
	public partial class File : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "File";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public File(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<File, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload file
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public object UmbracoFile
		{
			get { return this.GetPropertyValue("umbracoFile"); }
		}
	}

	/// <summary>Member</summary>
	[PublishedContentModel("Member")]
	public partial class Member : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Member";
		public new const PublishedItemType ModelItemType = PublishedItemType.Member;
#pragma warning restore 0109

		public Member(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Member, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Is Approved
		///</summary>
		[ImplementPropertyType("umbracoMemberApproved")]
		public bool UmbracoMemberApproved
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberApproved"); }
		}

		///<summary>
		/// Comments
		///</summary>
		[ImplementPropertyType("umbracoMemberComments")]
		public string UmbracoMemberComments
		{
			get { return this.GetPropertyValue<string>("umbracoMemberComments"); }
		}

		///<summary>
		/// Failed Password Attempts
		///</summary>
		[ImplementPropertyType("umbracoMemberFailedPasswordAttempts")]
		public string UmbracoMemberFailedPasswordAttempts
		{
			get { return this.GetPropertyValue<string>("umbracoMemberFailedPasswordAttempts"); }
		}

		///<summary>
		/// Last Lockout Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLockoutDate")]
		public string UmbracoMemberLastLockoutDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLockoutDate"); }
		}

		///<summary>
		/// Last Login Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLogin")]
		public string UmbracoMemberLastLogin
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLogin"); }
		}

		///<summary>
		/// Last Password Change Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastPasswordChangeDate")]
		public string UmbracoMemberLastPasswordChangeDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastPasswordChangeDate"); }
		}

		///<summary>
		/// Is Locked Out
		///</summary>
		[ImplementPropertyType("umbracoMemberLockedOut")]
		public bool UmbracoMemberLockedOut
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberLockedOut"); }
		}

		///<summary>
		/// Password Answer
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalAnswer")]
		public string UmbracoMemberPasswordRetrievalAnswer
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalAnswer"); }
		}

		///<summary>
		/// Password Question
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalQuestion")]
		public string UmbracoMemberPasswordRetrievalQuestion
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalQuestion"); }
		}
	}

}
